In [1]:
import pandas as pd

In [2]:
df_list = pd.read_html("https://www.imdb.com/chart/top")

In [4]:
df_list[0]

,Unnamed: 0,Rank & Title,IMDb Rating,Your Rating,Unnamed: 4
0,NaN,1. Skazani na Shawshank (1994),9.2,12345678910 NOT YET RELEASED Seen,NaN
1,NaN,2. Ojciec chrzestny (1972),9.1,12345678910 NOT YET RELEASED Seen,NaN
2,NaN,3. Ojciec chrzestny II (1974),9.0,12345678910 NOT YET RELEASED Seen,NaN
3,NaN,4. Mroczny Rycerz (2008),9.0,12345678910 NOT YET RELEASED Seen,NaN
4,NaN,5. Dwunastu gniewnych ludzi (1957),8.9,12345678910 NOT YET RELEASED Seen,NaN
...,...,...,...,...,...
245,NaN,246. Narzeczona dla księcia (1987),8.0,12345678910 NOT YET RELEASED Seen,NaN
246,NaN,247. Noce Cabirii (1957),8.0,12345678910 NOT YET RELEASED Seen,NaN
247,NaN,"248. Paryż, Teksas (1984)",8.0,12345678910 NOT YET RELEASED Seen,NaN
248,NaN,249. Trzy kolory: Czerwony (1994),8.0,12345678910 NOT YET RELEASED Seen,NaN
249,NaN,250. Mandarynki (2013),8.0,12345678910 NOT YET RELEASED Seen,NaN

In [5]:
!pip install requests

Requirement already satisfied: requests in c:\users\kurs\anaconda3\lib\site-packages (2.25.1)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\kurs\anaconda3\lib\site-packages (from requests) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\kurs\anaconda3\lib\site-packages (from requests) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\kurs\anaconda3\lib\site-packages (from requests) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kurs\anaconda3\lib\site-packages (from requests) (2020.12.5)

In [6]:
!pip install bs4

Collecting bs4
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
Requirement already satisfied: beautifulsoup4 in c:\users\kurs\anaconda3\lib\site-packages (from bs4) (4.9.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\kurs\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.2.1)
Building wheels for collected packages: bs4
  Building wheel for bs4 (setup.py): started
  Building wheel for bs4 (setup.py): finished with status 'done'
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1273 sha256=a86d4733fd5c0a9cd88b67e6624af53443d02d63af6ed2136177249ac00c3115
  Stored in directory: c:\users\kurs\appdata\local\pip\cache\wheels\75\78\21\68b124549c9bdc94f822c02fb9aa3578a669843f9767776bca
Successfully built bs4
Installing collected packages: bs4
Successfully installed bs4-0.0.1

In [11]:
!pip install lxml

Requirement already satisfied: lxml in c:\users\kurs\anaconda3\lib\site-packages (4.6.3)

In [7]:
import requests
import bs4

In [8]:
# pobranie HTMLa z wskazanego URLa
response = requests.get("https://www.imdb.com/chart/top")

In [10]:
# przekształcenie HTMLa do DOM (Document Object Model)
dom = bs4.BeautifulSoup(response.text)

In [13]:
tbody = dom.find("tbody", class_="lister-list") # pobranie zawartości tabeli wg znacznika TBODY i nazwy klasy

In [15]:
rows = tbody.find_all("tr") # ekstrakcja wierszy z tabeli

In [45]:
#rows[0].find("td", class_="titleColumn").find("a").get("href")
rows[0].find("td", class_="posterColumn").find("img").get("src")

'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UY67_CR0,0,45,67_AL_.jpg'

In [46]:
result = []
for row in rows:
    rank = row.find("span").get("data-value")
    link = row.find("td", class_="titleColumn").find("a").get("href")
    title = row.find("td", class_="titleColumn").find("a").text
    year = row.find("td", class_="titleColumn").find("span").text[1:-1]
    rating = row.find("td", class_="ratingColumn").text.strip()
    img = row.find("td", class_="posterColumn").find("img").get("src")
    #print(rank, title, link, year, rating, sep=";")
    movie = {
        "rank" : rank, "title" : title, "link" : link, "year" : year,
        "rating" : rating, "img" : img
    }
    result.append(movie)

In [48]:
df = pd.DataFrame(result)
df

,rank,title,link,year,rating,img
0,1,Skazani na Shawshank,/title/tt0111161/,1994,9.2,https://m.media-amazon.com/images/M/MV5BMDFkYT...
1,2,Ojciec chrzestny,/title/tt0068646/,1972,9.1,https://m.media-amazon.com/images/M/MV5BM2MyNj...
2,3,Ojciec chrzestny II,/title/tt0071562/,1974,9.0,https://m.media-amazon.com/images/M/MV5BMWMwMG...
3,4,Mroczny Rycerz,/title/tt0468569/,2008,9.0,https://m.media-amazon.com/images/M/MV5BMTMxNT...
4,5,Dwunastu gniewnych ludzi,/title/tt0050083/,1957,8.9,https://m.media-amazon.com/images/M/MV5BMWU4N2...
...,...,...,...,...,...,...
245,246,Narzeczona dla księcia,/title/tt0093779/,1987,8.0,https://m.media-amazon.com/images/M/MV5BMGM4M2...
246,247,Noce Cabirii,/title/tt0050783/,1957,8.0,https://m.media-amazon.com/images/M/MV5BOTdhNm...
247,248,"Paryż, Teksas",/title/tt0087884/,1984,8.0,https://m.media-amazon.com/images/M/MV5BM2RjMm...
248,249,Trzy kolory: Czerwony,/title/tt0111495/,1994,8.0,https://m.media-amazon.com/images/M/MV5BYTg1Mm...
249,250,Mandarynki,/title/tt2991224/,2013,8.0,https://m.media-amazon.com/images/M/MV5BMTgwNz...

In [50]:
df.link = "https://imdb.com" + df.link
df

,rank,title,link,year,rating,img
0,1,Skazani na Shawshank,https://imdb.com/title/tt0111161/,1994,9.2,https://m.media-amazon.com/images/M/MV5BMDFkYT...
1,2,Ojciec chrzestny,https://imdb.com/title/tt0068646/,1972,9.1,https://m.media-amazon.com/images/M/MV5BM2MyNj...
2,3,Ojciec chrzestny II,https://imdb.com/title/tt0071562/,1974,9.0,https://m.media-amazon.com/images/M/MV5BMWMwMG...
3,4,Mroczny Rycerz,https://imdb.com/title/tt0468569/,2008,9.0,https://m.media-amazon.com/images/M/MV5BMTMxNT...
4,5,Dwunastu gniewnych ludzi,https://imdb.com/title/tt0050083/,1957,8.9,https://m.media-amazon.com/images/M/MV5BMWU4N2...
...,...,...,...,...,...,...
245,246,Narzeczona dla księcia,https://imdb.com/title/tt0093779/,1987,8.0,https://m.media-amazon.com/images/M/MV5BMGM4M2...
246,247,Noce Cabirii,https://imdb.com/title/tt0050783/,1957,8.0,https://m.media-amazon.com/images/M/MV5BOTdhNm...
247,248,"Paryż, Teksas",https://imdb.com/title/tt0087884/,1984,8.0,https://m.media-amazon.com/images/M/MV5BM2RjMm...
248,249,Trzy kolory: Czerwony,https://imdb.com/title/tt0111495/,1994,8.0,https://m.media-amazon.com/images/M/MV5BYTg1Mm...
249,250,Mandarynki,https://imdb.com/title/tt2991224/,2013,8.0,https://m.media-amazon.com/images/M/MV5BMTgwNz...